stages:
 - build
 - test
 - deploy
 
variables:
 GIT_STRATEGY: none
 ANSIBLE_DIR: "/home/ubuntu/staking-iac/ansible"
 ANSIBLE_REPO: "/home/ubuntu/staking-iac/"

.BuildJSApp:
 stage: build
 script:
  # Update new ansible source
#   - cd ${ANSIBLE_REPO}
#   - sudo su ubuntu -c "git reset --hard HEAD"
#   - sudo su ubuntu -c "git checkout terraform"
#   - sudo su ubuntu -c "export GIT_SSH_COMMAND='ssh -i /home/ubuntu/staking-iac/ansible/id_rsa';git pull"
  # Run ansible-playbook
  - cd ${ANSIBLE_DIR}
  - ansible_file=`grep ${CI_PROJECT_NAME}.git *.yml | awk '{print $1}'|awk -F':' '{print $1}' | grep ${_ENV}`
  - sudo su ubuntu -c "ansible-playbook $ansible_file --extra-vars=\"node_git_version=${CI_COMMIT_TAG}\""

.OnlyStaging:
 only:
  - /^.*-rc$/
 except:
  - branches

.OnlyProduction:
 only:
  - /^.*[0-9]$/
 except:
  - branches

StageMoonStake:
 variables:
  _ENV: "stage" 
 extends:
  - .BuildJSApp
  - .OnlyStaging
 tags:
  - stage-stak-mp-ansible

ProdMoonStake:
 variables:
  _ENV: "prod" 
 extends:
  - .BuildJSApp
  - .OnlyProduction
 tags:
  - prod-stak-mp-ansible 
